-- 物业账单管理系统 MySQL 数据库结构
-- 创建数据库：CREATE DATABASE property_billing CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','user') NOT NULL DEFAULT 'admin',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settings (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_name VARCHAR(200) NOT NULL DEFAULT '示例物业服务有限公司',
  phone VARCHAR(50) DEFAULT '0571-88888888',
  bank_name VARCHAR(200) DEFAULT '中国工商银行杭州分行',
  account_holder VARCHAR(200) DEFAULT '示例物业服务有限公司',
  bank_account VARCHAR(100) DEFAULT '1202 0200 0990 0000 000',
  wechat_qr LONGTEXT,
  alipay_qr LONGTEXT,
  seal_image LONGTEXT,
  due_days INT NOT NULL DEFAULT 5,
  reminder_note TEXT,
  footer_note TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tenants (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  room VARCHAR(200) NOT NULL,
  phone VARCHAR(50) DEFAULT '',
  contract_start DATE DEFAULT NULL,
  contract_end DATE DEFAULT NULL,
  rent DECIMAL(12,2) NOT NULL DEFAULT 0,
  parking DECIMAL(12,2) NOT NULL DEFAULT 0,
  garbage DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meters (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  name VARCHAR(200) NOT NULL,
  type ENUM('electricity','water') NOT NULL,
  price DECIMAL(12,4) NOT NULL DEFAULT 0,
  unit VARCHAR(20) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS readings (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  meter_id VARCHAR(36) NOT NULL,
  month CHAR(7) NOT NULL,
  value DECIMAL(12,2) NOT NULL DEFAULT 0,
  reading_time DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_meter_month (meter_id, month),
  FOREIGN KEY (meter_id) REFERENCES meters(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
